[package]
name = "yum-osu"
version = "0.2.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14", features = ["dynamic_linking"] }
bevy_kira_audio = "0.20"
rand = "0.8.5"
rayon = "1.10.0"
aubio = "0.2.1"
biquad = "0.4.2"

[profile.dev]
opt-level = 1
[profile.dev.package."*"]
opt-level = 3
